import streamlit as st


def render_career():

    st.markdown("# 🚀 AI Career Roadmap")
    st.caption("Your personalized roadmap generated by AI")

    st.divider()

    st.markdown("""
<div style="
background:#1E293B;
padding:25px;
border-radius:20px;
border-left:6px solid #2563EB;
">

<h3>🎯 Your Learning Journey</h3>

Follow this roadmap step-by-step to become industry ready.

</div>
""", unsafe_allow_html=True)

    st.write("")

    if st.session_state.roadmap:

        st.markdown(f"""
<div style="
background:#111827;
padding:30px;
border-radius:20px;
border:1px solid #334155;
line-height:2;
font-size:17px;
">

{st.session_state.roadmap}

</div>
""", unsafe_allow_html=True)

    else:

        st.warning("Career roadmap is not available.")